language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y dmtx-utils

script: phpunit --coverage-text
