language: php

php:
    - 7.2

before_script:
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y dmtx-utils

script: phpunit --coverage-text
